# Generated by Django 4.1.9 on 2023-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwtToken',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
