# Generated by Django 4.1.9 on 2023-05-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_jwttoken'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='addedBy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
